
# syntax:docker/dockerfile:1

FROM alpine:3.8

RUN apk --no-cache add \
    php7.3 php7.3-cgi php7.3-ctype php7.3-json php7.3-dom php7.3-zip php7.3-zip php7.3-gd \
    php7.3-curl php7.3-mbstring php7.3-redis php7.3-mcrypt php7.3-iconv php7.3-posix php7.3-pdo_mysql php7.3-tokenizer php7.3-simplexml php7.3-session \
    php7.3-xml php7.3-sockets php7.3-openssl php7.3-fileinfo php7.3-ldap php7.3-exif php7.3-pcntl php7.3-xmlwriter php7.3-phar php7.3-zlib \
    php7.3-intl

RUN apk --no-cache add wget \
    && wget https://github.com/spiral/roadrunner/releases/download/v1.3.2/roadrunner-1.3.2-linux-amd64.tar.gz \
    && apk del --purge wget \
    && tar -xvzf roadrunner-1.3.2-linux-amd64.tar.gz \
    && mv roadrunner-1.3.2-linux-amd64 roadrunner \
    && rm roadrunner-1.3.2-linux-amd64.tar.gz

ENTRYPOINT ["/roadrunner/rr"]

CMD ["-c /var/www/.rr.yml", "serve"]